[OUT-2528] Makefile targets and RPM spec file for oa-build.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -19,3 +19,36 @@ README: README.md
 
 clean-local:
 	$(RM) README
+
+
+# -------- Outside Analytics Additions -------
+buildchk:
+	@if [[ ! -n $$VERSION ]] || [[ ! -n $$RELEASE ]]; \
+	then \
+	  echo "Usage: make rpm \"VERSION=x.y.z\" \"RELEASE=n\""; \
+	  exit 1; \
+	fi
+
+rpm: buildchk
+	@mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
+	@if [[ -n `git tag --list ${VERSION}` ]]; \
+	then \
+	  echo "Extracting git archive for tag: ${VERSION}"; \
+	  git archive --format tar.gz \
+	              --output=rpmbuild/SOURCES/proj-${VERSION}.tar.gz \
+	              --prefix=proj-${VERSION}/ \
+	              ${VERSION}; \
+	else \
+	  echo "Extracting git archive for HEAD (tag not found for: ${VERSION})"; \
+	  git archive --format tar.gz \
+	              --output=rpmbuild/SOURCES/proj-${VERSION}.tar.gz \
+	              --prefix=proj-${VERSION}/ \
+	              HEAD; \
+	fi
+	sed -e 's,xVERSIONx,${VERSION},' \
+	    -e 's,xRELEASEx,${RELEASE},' \
+	    proj6.spec >| rpmbuild/SPECS/proj6.spec
+	cd rpmbuild/SPECS; \
+	  rpmbuild --define "_topdir $$PWD/.." -ba proj6.spec
+	@echo "Makefile.rpm done. Result in: $$PWD/rpmbuild/RPMS/x86_64"
+
